[default]
out = "artifacts"
optimizer = true
optimizer_runs = 10000
cache = false
force = true
verbosity = 3
fuzz_runs = 100

[default.optimizer_details]
yul = true

[ci]
fuzz-runs = 10_000

# See more config options https://github.com/gakonst/foundry/tree/master/config
