name: CI 

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

env:
  FOUNDRY_PROFILE: ci

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: make

      - name: Run lint check
        run: make lint
      
      # TODO: implement repo secrets to we can do mainnet forks for integration tests and other parameter configuration
      - name: Run tests
        run: forge test

      - name: Run Slither
        uses: crytic/slither-action@main
        id: slither
        continue-on-error: true
        with:
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
